### PR TITLE
enable warnings & warnings as errors in tests

### LINKED ISSUE #86: Add stricter compile flags when building tests
To make `Tileson` more clean and less error prone, the flags `-Wall -Wextra -Werror` should be added to the test build, to make CI a stricter process. This will be done after the CI is fixed and a proper `MAC` build using `Clang` is implemented.

See #84 for the discussion.

Big thanks to @dmlary for the suggestion :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by dmlary**
Add `-Wall -Wextra -Werror` to tileson_tests build target, along with (I think) the eqivalent for MSVC.

Include quick fixes for existing tests, which may not be the best solution.  Committing this to see what comes out of CI.

fixed #86

### CODE REVIEW

**Comment by SSBMTonberry** [comment]
I can have a look at the `C4244 warning` from `MSVC`. :slightly_smiling_face:

**Comment by SSBMTonberry** [comment]
Well great... Seems like some of the stuff I added was not completely supported by all compilers. I'll fix that. Sorry 😛

**Comment by SSBMTonberry** [comment]
Seems like the rest is GCC related. Since that's my main compiler anyways I can have a quick look 🙂

**Comment by SSBMTonberry** [comment]
Last error seems to be related to `[[maybe_unused]]` not being fully implemented for structured bindings in `GCC7`.
Ref: https://stackoverflow.com/questions/47005032/structured-bindings-and-range-based-for-supress-unused-warning-in-gcc

**Comment by dmlary** [comment]
oh, nice!  Looks like you've knocked out most of it.

The dumb fix for gcc7 is to just use that other variable.  I wonder if the old-school cast-to-void (`(void)var`) will get us past the hump.  Failing that, there's a C++ construct we can use: https://stackoverflow.com/a/3418951

**Comment by SSBMTonberry** [comment]
> oh, nice! Looks like you've knocked out most of it.
> 
> The dumb fix for gcc7 is to just use that other variable. I wonder if the old-school cast-to-void (`(void)var`) will get us past the hump. Failing that, there's a C++ construct we can use: https://stackoverflow.com/a/3418951

Seems like the `(void)` cast "hack" does the job. It's not pretty, but honestly it's just to make it shut up when a variable is intentionally unused, and `GCC7` has a missing support for a case that should work. Just to make the tests work I think it's okay, though it's very ugly :stuck_out_tongue_closed_eyes:

**Comment by SSBMTonberry** [comment]
All tests passes now!

To summarize: 
- Warnings found related to `external/gason.hpp` and `extras/pocketlzma.hpp` are ignored in these specific files, as they are external libraries. Since `PocketLzma` is a library I maintain, I will have a look at that specific issue in that project, but `Gason` is not maintained by me, is not supported by `Tileson`, and is unlikely to ever change based on its history.
- I had put some demo code in `tests_main.cpp` in the end, that had the sole purpose of being visual and descriptive, but would produce warnings for unused variables etc. I'll let the changes done pass, but I'll probably move this out to another file with those checks disabled eventually for this purpose.
- Some minor improvements has been made as a result of more strict handling of warnings, so that's nice.
- Added a conditional `(void)variable` cast for `GCC7` due to missing `[[maybe_unused]]` for structured bindings. It's not pretty, but it gets the job done.
- The `unused variable` related warnings feels more annoying than useful, but at the same time it makes us aware of cases where variables are unintentionally created and unused, which should be most cases in a real world scenario, so I guess it's okay to have it on.
- Feels like it's manageable to have warnings as errors with additional warning reports for tests, so all in all it should be okay to keep it on. It should make `Tileson` a potentially more stable library, and it shouldn't produce too much annoying warnings for the users of the library.

@dmlary : If you got anything to add, feel free to do so. :slightly_smiling_face:

**Comment by dmlary** [comment]
Everything looks good. My goal is achieved here, and I have nothing more to add. 

Great work sorting through all those msvc and gcc errors!

**Comment by SSBMTonberry** [comment]
> Everything looks good. My goal is achieved here, and I have nothing more to add.
> 
> Great work sorting through all those msvc and gcc errors!

Then I guess it ready for a merge!
This ended up being a nice cooperation task :smile: 
Thank you very much for your help, and a great initiative :partying_face:

**Pull request merged**
