### PR TITLE
Changed to use generic_string so that it can build under c++ 20

### PR DESCRIPTION
**Pull request by gamecoder-nz**
I have run all tests and examples and they work

### CODE REVIEW

**Comment by gamecoder-nz** [comment]
#53

**Comment by SSBMTonberry** [comment]
Hello again!
Please feel free to keep this PR open. It should update with the branch you are using, though I would suggest to create a feature branch instead of pushing directly from your main 🙂 

In short: When I changed the `set(CMAKE_CXX_STANDARD 17)` to `set(CMAKE_CXX_STANDARD 20)` in the `CMakeLists.txt` files located in the root folder, `/examples/sfml` and `/tests` there were still some compile errors related to C++17 code. I guess you probably just forgot to change the C++ version before compiling and testing 🙂 

I see `tileson.hpp` and `tileson_min.hpp` also was not up to date. I suggest you find the script thought PowerShell or your go to terminal and try to run it from there. If you are on OSX there is sadly no working script for this, but just tell me if that's the case, and I can run it for you.

If you're on windows, you should be fine just by going into the `tools` folder and run it like this:
image

Lastly:
When I turned on the `option(BUILD_EXAMPLES "Build examples." ON)` (after locally upodating the `tileson.hpp` through the script, the examples didn't build either. Partly due to the u8string(), probably, but it might also be that `SFML` is outdated and we would need to get the latest SFML version from their `master` branch.

**Comment by gamecoder-nz** [comment]
I have pushed more changes so that everything builds

**Comment by SSBMTonberry** [comment]
Well done! I've tested your change on Windows and Linux, and it seems to work great.
Thank you very much :smile:

**Pull request merged**
