### PR TITLE
Support loading tileset properties from multiple tilesets

### LINKED ISSUE #54: Tile properties are only loaded for first tileset
Hi,

It seems that tile properties are only parsed for the first tileset and ignored for all following tilesets. The data is correctly written by Tiled and present in the json.
However tileson does not seem to parse the property information correctly for the second tileset.

I will attach a minimal working example json in the next comment. Please find the screenshot of the debugging information of the map here:

tested on the current master, commit id a1ec661aeca7144985b902283b2a6dc92b8ee854

image

### PR DESCRIPTION
**Pull request by Laguna1989**
Will fix #54 

I have added the example json tilemap from the issue. 

It seems that the issue is created by the `Tileset::generateMissingTiles()` member function, which I do not fully understand. This function causes the tileset to contain multiple tiles with the same `gid`. This seems like a weird idea, but quite some tests are relying on this functionality. 

As the additionally created "missing" tiles are emplaced at the end of the tiles vector, I created a workaround in the `Map::processData()` function. Only the first tile with a gid will be used, all further tiles with the same `gid` will now be ignored. This kept the already existing tests green while also satisfying the expectations in the newly created test case.

### CODE REVIEW

**Comment by Laguna1989** [comment]
I have added the example json tilemap from the issue. 

It seems that the issue is created by the `Tileset::generateMissingTiles()` member function, which I do not fully understand. This function causes the tileset to contain multiple tiles with the same `gid`. This seems like a weird idea, but quite some tests are relying on this functionality. 

As the additionally created "missing" tiles are emplaced at the end of the tiles vector, I created a workaround in the `Map::processData()` function. Only the first tile with a gid will be used, all further tiles with the same `gid` will now be ignored. This kept the already existing tests green while also satisfying the expectations in the newly created test case.

**Comment by SSBMTonberry** [comment]
Ggreat job! 

I'll have to get back to this after work, but I'll have a look and eventually merge it :smile: 
Long story short about `Tileset::generateMissingTiles()`: When tiles have no properties in Tiled they are not mentioned in the `json` file. That's the reason why this function exists: If you would use a simple tile without any properties you would get a crash as a result. With that said: This function has never been intended to produce several `duplicates` of the same `gid`, so pretty sure that was a bug :slightly_smiling_face:

**Comment by SSBMTonberry** [comment]
Ok, so I did a simble test locally to verify that the example compiles and works well. Unfortunately I was not able to run any tests using `GCC 11.2`, but that is an issue between `Catch2` and `GCC`, and unrelated to your fix. The `CI` you implemented in your previous feature says it's all good, so I'll accept this and merge it.

Sorry for taking so long time before I could verify this. Your work is much appreciated!

**Comment by Laguna1989** [comment]
Thanks for merging the PR. Will get great use in our next gamejam. Have a great weekend! :)

**Comment by SSBMTonberry** [comment]
Have a great weekend, and thank you again for your contribution! :smile: 
It really helps out in times where I don't have as much time as I want to maintain certain projects.

**Pull request merged**
